apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-metric-test
  namespace: default
  labels:
    app: python-metric-test
spec:
  selector:
    matchLabels:
      app: python-metric-test
  replicas: 1
  template:
    metadata:
      labels:
        app: python-metric-test
    spec:
      containers:
      - name: python-metric-test
        image:  localhost/metric-python-test:alpha0.2
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  80
          name: http
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: python-metric-test
  namespace: default
spec:
  selector:
    app: python-metric-test
  ports:
  - port: 80
    targetPort: 80
